const geographic_area = {
    "Canada":{
        "Alberta":{},
        "British Columbia":{},
        "Manitoba":{},
        "New Brunswick":{},
        "Newfoundland and Labrador":{},
        "Nova Scotia":{},
        "Northwest Territories":{},
        "Nunavut":{},
        "Ontario":["Barrie",
            "Belleville",
            "Brampton",
            "Brant",
            "Brantford",
            "Brockville",
            "Burlington",
            "Cambridge",
            "Clarence-Rockland",
            "Cornwall",
            "Dryden",
            "Elliot Lake",
            "Greater Sudbury",
            "Guelph",
            "Haldimand County",
            "Hamilton",
            "Kawartha Lakes",
            "Kenora",
            "Kingston",
            "Kitchener",
            "London",
            "Markham",
            "Mississauga",
            "Niagara Falls",
            "Norfolk County",
            "North Bay",
            "Orillia",
            "Oshawa",
            "Ottawa",
            "Owen Sound",
            "Pembroke",
            "Peterborough",
            "Pickering",
            "Port Colborne",
            "Prince Edward County",
            "Quinte West",
            "Richmond Hill",
            "Sarnia",
            "Sault Ste. Marie",
            "St. Catharines",
            "St. Thomas",
            "Stratford",
            "Temiskaming Shores",
            "Thorold",
            "Thunder Bay",
            "Timmins",
            "Toronto",
            "Vaughan",
            "Waterloo",
            "Welland",
            "Windsor",
            "Woodstock"],
        "Prince Edward Island":{},
        "Québec":{},
        "Saskatchewan":{},
        "Yukon":{}
    }
};

const category = {
    "All Categories":{
        "Buy & Sell":{},
        "Cars & Vehicles":{},
        "Real Estate":{
            "For Sale":{},
            "For Rent":{}
        }, 
        "Services":{},
        "Pets":{},
        "Jobs":{},
        "Community":{}
    }
};

module.exports = {"geographic_area":geographic_area, "category":category};